### ISSUE TITLE
Support for Html Headers in Table Organism

### ISSUE THREAD

**Issue by AParks** [ZengineHQ/plugin-sdk#40]
Current <Table> component in `zengine-ui-react` only supports passing an array of strings to the Headers prop
Would be nice to allow ReactElements as well. such as a checkbox for a "Select All" action

https://zenginehq.github.io/plugin-sdk/?path=/docs/components-organisms-table--default

**Comment by wizehive-chrismanjoine** [comment]
released in version 0.21.0
